# Config file for PaperNicks by Majekdor | Have questions? Ask here: https://discord.majek.dev

# Whether or not nicknames should show in the tab list
tab-nicks: false

# The maximum number of characters (excluding color codes) a nickname may be
max-length: 20

# The minimum number of characters (excluding color codes) a nickname may be
min-length: 3

# Whether or not to support legacy nicknames (&a, &l, etc.)
legacy: false

# This should only be enabled if the developer needs additional information about plugin issues
debug: false


# Message configuration
messages:
  invalidSender: "<red>You must be in-game to use this command."
  tooShort: "<red>That nickname is too short. Minimum length is %length% characters."
  tooLong: "<red>That nickname is too long. Maximum length is %length% characters."